# Controller for differential drive wheel systems 
# http://wiki.ros.org/diff_drive_controller

type: "diff_drive_controller/DiffDriveController"
publish_rate: 50

left_wheel: ['front_left_wheel_joint', 'rear_left_wheel_joint']
right_wheel: ['front_right_wheel_joint', 'rear_right_wheel_joint']

# Wheel separation and diameter. These are both optional.
# diff_drive_controller will attempt to read either one or both from the
# URDF if not specified as a parameter
wheel_separation : 0.45 #[m]
wheel_radius : 0.06     #[m]

enable_odom_tf: true
# Odometry covariances for the encoder output of the robot. These values should
# be tuned to your robot's sample odometry data, but these values are a good place
# to start
pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

# Top level frame (link) of the robot description
base_frame_id: base_link

# Velocity and acceleration limits for the robot
linear:
  x:
    has_velocity_limits    : true
    max_velocity           : 2.0   # m/s
    has_acceleration_limits: true
    max_acceleration       : 1.0   # m/s^2
angular:
  z:
    has_velocity_limits    : true
    max_velocity           : 8.0   # rad/s
    has_acceleration_limits: true
    max_acceleration       : 2.0   # rad/s^2
