gazebo_ros_control:   
  pid_gains:
    front_wheel_left_joint:
      p: 1.
      i: 0 
      d: 0
    front_wheel_right_joint:
      p: 1.
      i: 0 
      d: 0
    rear_wheel_left_joint:
      p: 1.
      i: 0
      d: 0
    rear_wheel_right_joint:
      p: 1.
      i: 0
      d: 0