gazebo_ros_control:   
  pid_gains:
    front_left_wheel_joint:
      p: 1.
      i: 0 
      d: 0
    front_right_wheel_joint:
      p: 1.
      i: 0 
      d: 0
    rear_left_wheel_joint:
      p: 1.
      i: 0
      d: 0
    rear_right_wheel_joint:
      p: 1.
      i: 0
      d: 0